services:
  - type: web
    name: gaming-championship-judging
    env: native
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gaming-championship-db
          property: connectionString

databases:
  - name: gaming-championship-db
    databaseName: judging_syatem
    user: judging_user